### ISSUE TITLE
Building nightly

### ISSUE THREAD

**Issue by sillevl** [INTI-CMNB/kicad_debian#1]
I want to use `kicad_auto` with some projects I have. I have used a recent version 
`Version: (5.99.0-9827-g1cfefb0652), release build` Build on `Mar 17 2021 22:00:40`

In order to have some tools working, I need a later version of KiCad (Feb 28 2021 is included now).
I tried creating updated docker containers, but I get the following error while building the nightly of this project.

```cli
#8 38.32 Some packages could not be installed. This may mean that you have
#8 38.32 requested an impossible situation or if you are using the unstable
#8 38.32 distribution that some required packages have not yet been created
#8 38.32 or been moved out of Incoming.
#8 38.32 The following information may help to resolve the situation:
#8 38.32
#8 38.32 The following packages have unmet dependencies:
#8 38.39  kicad-nightly : Depends: libc6 (>= 2.33) but 2.31-11 is to be installed
#8 38.40 E: Unable to correct problems, you have held broken packages.
```

As I understand, libc6 v2.33 is not yet available in debian...

**Comment by set-soft** [comment]
Hi @sillevl !

True, the "nightly" version of the docker image isn't building. 

I'm working on integrating KiCost to KiBot, which is much harder than what I thought. The KiCad 5.99 support isn't updated. I'm quite sure that KiAuto and KiBot will fail with a new version of KiCad 5.99 because it changes all the time, and the policy is to avoid any kind of compatibility additions. 

I'll take a look at this when I find some time, I think solving the build issues will be simple (I have KiCad 5.99 installed on my Debian machine), but updating KiAuto/KiBot will take much more time.

**Comment by sillevl** [comment]
@set-soft thank you for your reply. I understand that KiCad 5.99 might have breaking changes in future releases and that it might render some efforts worthless. 

I had tried using the ubuntu deb package of libc6, this seemd to work, but opened another can of worms... I don't have alot of experience in that domain.

Thank you for your efforts in this project and I look forward to use it in the future.

**Comment by set-soft** [comment]
@sillevl I updated the Dockerfiles, the build is queued at docker hub. It worked on my system. But again: This will only update KiCad, but will break KiAuto/KiBot.

**Comment by sillevl** [comment]
@set-soft thank you! I will take a look. This might solve my problems for now...

**Comment by set-soft** [comment]
Nightly is building ok and is now in a workflow here.
