### ISSUE TITLE
[FEATURE] Dark mode

### ISSUE THREAD

**Issue by Nudelsalad** [INTI-CMNB/kicad_debian#4]
Hi there, 
This is more of a question than a feature request but I would like to know if anyone has managed to get the Kicad container to run in dark mode.
I have already tried several things and it seems to work fine, but somehow X11 or something else overrides the dark mode and it gets minimal grey ish but still toooo white :sob:

![Screenshot from 2023-11-02 10-25-20](https://github.com/INTI-CMNB/kicad_debian/assets/64224137/fcc6dc08-8394-4ee0-8437-9df627b77a64)

Running Pop!OS 22.04 LTS with Gnome

Things I've tried include
Setting up GTK3.0 with ~/.config/gtk3.0/settings.ini with 
[settings]
gtk-application-prefer-dark-theme=1 

Would be nice to get some support on this, although it seems to be more of a Linux issue than a Kicad one. But may be useful for others as well.
Thanks in advance, appreciate any help

**Comment by set-soft** [comment]
Hi @Nudelsalad !

I think the problem here is where things get rendered. If I run my local copy of KiCad I get:

![image](https://github.com/INTI-CMNB/kicad_debian/assets/22823627/9c2c47a0-6b5a-4a7f-a595-8bb039645a56)

But if I run it from the docker image I get:

![image](https://github.com/INTI-CMNB/kicad_debian/assets/22823627/ae7ac6d4-1006-41b5-ad50-8ff77806d05f)

Here you can see two major differences:

1. Colors
2. Language

The docker image doesn't even have the spanish locales, so you can't even switch the language.

I'm not sure where does KiCad get the colors, but the problem is that something is missing in the docker image. I think this is something related with the GTK theme. In my GNOME I have "Adwaita-dark".

In my particular case I got it solved installing the *gnome-themes-extra-data* package in the docker image. Does it solves your case?

**Comment by Nudelsalad** [comment]
Thank you for your response, I am pretty sure that you're absolutely right. I guess I just made to much changes on my hostsystem to getting my container into dark-mode even with the extra package installed. I can close this "issue" now as you added this package to the full image.
Thanks @set-soft for your awesome work!
